#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
生成完整的四六级词库数据
CET-4: 约2000个核心词汇
CET-6: 约1500个核心词汇
"""

import json
import os


def generate_cet4_words():
    """生成CET-4核心词汇"""
    words = [
        # A (100词)
        {
            "word": "abandon",
            "phonetic": "/əˈbændən/",
            "part_of_speech": "v.",
            "definition": "放弃，遗弃",
            "english_definition": "to leave behind, desert",
            "difficulty": 2,
        },
        {
            "word": "ability",
            "phonetic": "/əˈbɪləti/",
            "part_of_speech": "n.",
            "definition": "能力，才能",
            "english_definition": "the power or capacity to do something",
            "difficulty": 1,
        },
        {
            "word": "abnormal",
            "phonetic": "/æbˈnɔːrml/",
            "part_of_speech": "adj.",
            "definition": "反常的，异常的",
            "english_definition": "deviating from what is normal",
            "difficulty": 2,
        },
        {
            "word": "aboard",
            "phonetic": "/əˈbɔːrd/",
            "part_of_speech": "adv./prep.",
            "definition": "在船上，上船",
            "english_definition": "on or onto a ship, aircraft, train",
            "difficulty": 2,
        },
        {
            "word": "abolish",
            "phonetic": "/əˈbɒlɪʃ/",
            "part_of_speech": "v.",
            "definition": "废除，废止",
            "english_definition": "to formally put an end to",
            "difficulty": 3,
        },
        {
            "word": "abortion",
            "phonetic": "/əˈbɔːrʃn/",
            "part_of_speech": "n.",
            "definition": "流产，堕胎",
            "english_definition": "the deliberate termination of a pregnancy",
            "difficulty": 4,
        },
        {
            "word": "about",
            "phonetic": "/əˈbaʊt/",
            "part_of_speech": "prep./adv.",
            "definition": "关于，大约",
            "english_definition": "concerning, approximately",
            "difficulty": 1,
        },
        {
            "word": "above",
            "phonetic": "/əˈbʌv/",
            "part_of_speech": "prep./adv.",
            "definition": "在...上面",
            "english_definition": "at a higher level or layer",
            "difficulty": 1,
        },
        {
            "word": "abroad",
            "phonetic": "/əˈbrɔːd/",
            "part_of_speech": "adv.",
            "definition": "在国外，到国外",
            "english_definition": "in or to a foreign country",
            "difficulty": 1,
        },
        {
            "word": "absence",
            "phonetic": "/ˈæbsəns/",
            "part_of_speech": "n.",
            "definition": "缺席，不在",
            "english_definition": "the state of being away",
            "difficulty": 2,
        },
        {
            "word": "absent",
            "phonetic": "/ˈæbsənt/",
            "part_of_speech": "adj.",
            "definition": "缺席的，缺乏的",
            "english_definition": "not present",
            "difficulty": 2,
        },
        {
            "word": "absolute",
            "phonetic": "/ˈæbsəluːt/",
            "part_of_speech": "adj.",
            "definition": "绝对的，完全的",
            "english_definition": "complete, total",
            "difficulty": 2,
        },
        {
            "word": "absolutely",
            "phonetic": "/ˈæbsəluːtli/",
            "part_of_speech": "adv.",
            "definition": "完全地，绝对地",
            "english_definition": "completely, totally",
            "difficulty": 2,
        },
        {
            "word": "absorb",
            "phonetic": "/əbˈzɔːrb/",
            "part_of_speech": "v.",
            "definition": "吸收，吸引",
            "english_definition": "to take in, soak up",
            "difficulty": 2,
        },
        {
            "word": "abstract",
            "phonetic": "/ˈæbstrækt/",
            "part_of_speech": "adj./n.",
            "definition": "抽象的；摘要",
            "english_definition": "existing in thought; summary",
            "difficulty": 3,
        },
        {
            "word": "abundant",
            "phonetic": "/əˈbʌndənt/",
            "part_of_speech": "adj.",
            "definition": "丰富的，充裕的",
            "english_definition": "existing in large quantities",
            "difficulty": 2,
        },
        {
            "word": "abuse",
            "phonetic": "/əˈbjuːs/",
            "part_of_speech": "v./n.",
            "definition": "滥用，虐待",
            "english_definition": "to use wrongly; cruel treatment",
            "difficulty": 2,
        },
        {
            "word": "academic",
            "phonetic": "/ˌækəˈdemɪk/",
            "part_of_speech": "adj.",
            "definition": "学术的，学院的",
            "english_definition": "relating to education",
            "difficulty": 2,
        },
        {
            "word": "academy",
            "phonetic": "/əˈkædəmi/",
            "part_of_speech": "n.",
            "definition": "学院，研究院",
            "english_definition": "a place of study",
            "difficulty": 2,
        },
        {
            "word": "accelerate",
            "phonetic": "/əkˈseləreɪt/",
            "part_of_speech": "v.",
            "definition": "加速，促进",
            "english_definition": "to increase speed",
            "difficulty": 3,
        },
        {
            "word": "accent",
            "phonetic": "/ˈæksent/",
            "part_of_speech": "n.",
            "definition": "口音，重音",
            "english_definition": "a distinctive way of pronouncing",
            "difficulty": 2,
        },
        {
            "word": "accept",
            "phonetic": "/əkˈsept/",
            "part_of_speech": "v.",
            "definition": "接受，认可",
            "english_definition": "to agree to take",
            "difficulty": 1,
        },
        {
            "word": "acceptable",
            "phonetic": "/əkˈseptəbl/",
            "part_of_speech": "adj.",
            "definition": "可接受的，合意的",
            "english_definition": "satisfactory, adequate",
            "difficulty": 2,
        },
        {
            "word": "acceptance",
            "phonetic": "/əkˈseptəns/",
            "part_of_speech": "n.",
            "definition": "接受，接纳",
            "english_definition": "the action of accepting",
            "difficulty": 2,
        },
        {
            "word": "access",
            "phonetic": "/ˈækses/",
            "part_of_speech": "n./v.",
            "definition": "进入，使用；通道",
            "english_definition": "the means to approach",
            "difficulty": 2,
        },
        {
            "word": "accessible",
            "phonetic": "/əkˈsesəbl/",
            "part_of_speech": "adj.",
            "definition": "易接近的，可理解的",
            "english_definition": "able to be reached",
            "difficulty": 3,
        },
        {
            "word": "accident",
            "phonetic": "/ˈæksɪdənt/",
            "part_of_speech": "n.",
            "definition": "事故，意外",
            "english_definition": "an unfortunate incident",
            "difficulty": 1,
        },
        {
            "word": "accidental",
            "phonetic": "/ˌæksɪˈdentl/",
            "part_of_speech": "adj.",
            "definition": "意外的，偶然的",
            "english_definition": "happening by chance",
            "difficulty": 2,
        },
        {
            "word": "accommodate",
            "phonetic": "/əˈkɒmədeɪt/",
            "part_of_speech": "v.",
            "definition": "容纳，适应",
            "english_definition": "to provide lodging",
            "difficulty": 3,
        },
        {
            "word": "accommodation",
            "phonetic": "/əˌkɒməˈdeɪʃn/",
            "part_of_speech": "n.",
            "definition": "住处，膳宿",
            "english_definition": "a room or place to live",
            "difficulty": 3,
        },
        {
            "word": "accompany",
            "phonetic": "/əˈkʌmpəni/",
            "part_of_speech": "v.",
            "definition": "陪伴，伴随",
            "english_definition": "to go somewhere with",
            "difficulty": 2,
        },
        {
            "word": "accomplish",
            "phonetic": "/əˈkʌmplɪʃ/",
            "part_of_speech": "v.",
            "definition": "完成，实现",
            "english_definition": "to achieve successfully",
            "difficulty": 2,
        },
        {
            "word": "accord",
            "phonetic": "/əˈkɔːrd/",
            "part_of_speech": "v./n.",
            "definition": "一致，符合；协议",
            "english_definition": "agreement, harmony",
            "difficulty": 3,
        },
        {
            "word": "accordance",
            "phonetic": "/əˈkɔːdns/",
            "part_of_speech": "n.",
            "definition": "一致，按照",
            "english_definition": "conformity",
            "difficulty": 4,
        },
        {
            "word": "according",
            "phonetic": "/əˈkɔːrdɪŋ/",
            "part_of_speech": "adv.",
            "definition": "根据，按照",
            "english_definition": "as stated by",
            "difficulty": 1,
        },
        {
            "word": "accordingly",
            "phonetic": "/əˈkɔːrdɪŋli/",
            "part_of_speech": "adv.",
            "definition": "因此，相应地",
            "english_definition": "in a way that is appropriate",
            "difficulty": 3,
        },
        {
            "word": "account",
            "phonetic": "/əˈkaʊnt/",
            "part_of_speech": "n./v.",
            "definition": "账户，解释",
            "english_definition": "a record of transactions",
            "difficulty": 1,
        },
        {
            "word": "accountant",
            "phonetic": "/əˈkaʊntənt/",
            "part_of_speech": "n.",
            "definition": "会计，会计师",
            "english_definition": "a person who keeps accounts",
            "difficulty": 2,
        },
        {
            "word": "accumulate",
            "phonetic": "/əˈkjuːmjəleɪt/",
            "part_of_speech": "v.",
            "definition": "积累，积聚",
            "english_definition": "to gradually gather",
            "difficulty": 3,
        },
        {
            "word": "accumulation",
            "phonetic": "/əˌkjuːmjəˈleɪʃn/",
            "part_of_speech": "n.",
            "definition": "积累，堆积",
            "english_definition": "the acquisition of something",
            "difficulty": 3,
        },
        {
            "word": "accuracy",
            "phonetic": "/ˈækjərəsi/",
            "part_of_speech": "n.",
            "definition": "准确性，精确度",
            "english_definition": "the quality of being correct",
            "difficulty": 3,
        },
        {
            "word": "accurate",
            "phonetic": "/ˈækjərət/",
            "part_of_speech": "adj.",
            "definition": "准确的，精确的",
            "english_definition": "correct, exact",
            "difficulty": 2,
        },
        {
            "word": "accurately",
            "phonetic": "/ˈækjərətli/",
            "part_of_speech": "adv.",
            "definition": "准确地",
            "english_definition": "in a way that is correct",
            "difficulty": 2,
        },
        {
            "word": "accuse",
            "phonetic": "/əˈkjuːz/",
            "part_of_speech": "v.",
            "definition": "控告，指责",
            "english_definition": "to charge with an offense",
            "difficulty": 2,
        },
        {
            "word": "accustomed",
            "phonetic": "/əˈkʌstəmd/",
            "part_of_speech": "adj.",
            "definition": "习惯的，通常的",
            "english_definition": "usual, customary",
            "difficulty": 3,
        },
        {
            "word": "ache",
            "phonetic": "/eɪk/",
            "part_of_speech": "v./n.",
            "definition": "疼痛",
            "english_definition": "a continuous pain",
            "difficulty": 2,
        },
        {
            "word": "achieve",
            "phonetic": "/əˈtʃiːv/",
            "part_of_speech": "v.",
            "definition": "达到，实现",
            "english_definition": "to successfully reach",
            "difficulty": 1,
        },
        {
            "word": "achievement",
            "phonetic": "/əˈtʃiːvmənt/",
            "part_of_speech": "n.",
            "definition": "成就，成绩",
            "english_definition": "a thing done successfully",
            "difficulty": 2,
        },
        {
            "word": "acid",
            "phonetic": "/ˈæsɪd/",
            "part_of_speech": "n./adj.",
            "definition": "酸，酸的",
            "english_definition": "a chemical substance",
            "difficulty": 3,
        },
        {
            "word": "acknowledge",
            "phonetic": "/əkˈnɒlɪdʒ/",
            "part_of_speech": "v.",
            "definition": "承认，致谢",
            "english_definition": "to accept or admit",
            "difficulty": 3,
        },
        {
            "word": "acquaint",
            "phonetic": "/əˈkweɪnt/",
            "part_of_speech": "v.",
            "definition": "使熟悉，使了解",
            "english_definition": "to make familiar",
            "difficulty": 4,
        },
        {
            "word": "acquaintance",
            "phonetic": "/əˈkweɪntəns/",
            "part_of_speech": "n.",
            "definition": "熟人，相识",
            "english_definition": "a person one knows",
            "difficulty": 3,
        },
        {
            "word": "acquire",
            "phonetic": "/əˈkwaɪər/",
            "part_of_speech": "v.",
            "definition": "获得，学到",
            "english_definition": "to buy or obtain",
            "difficulty": 2,
        },
        {
            "word": "acquisition",
            "phonetic": "/ˌækwɪˈzɪʃn/",
            "part_of_speech": "n.",
            "definition": "获得，收购",
            "english_definition": "an asset obtained",
            "difficulty": 3,
        },
        {
            "word": "acre",
            "phonetic": "/ˈeɪkər/",
            "part_of_speech": "n.",
            "definition": "英亩",
            "english_definition": "a unit of land area",
            "difficulty": 3,
        },
        {
            "word": "across",
            "phonetic": "/əˈkrɒs/",
            "part_of_speech": "prep./adv.",
            "definition": "横过，穿过",
            "english_definition": "from one side to another",
            "difficulty": 1,
        },
        {
            "word": "act",
            "phonetic": "/ækt/",
            "part_of_speech": "v./n.",
            "definition": "行动，表演",
            "english_definition": "to take action",
            "difficulty": 1,
        },
        {
            "word": "action",
            "phonetic": "/ˈækʃn/",
            "part_of_speech": "n.",
            "definition": "行动，行为",
            "english_definition": "the process of doing",
            "difficulty": 1,
        },
        {
            "word": "activate",
            "phonetic": "/ˈæktɪveɪt/",
            "part_of_speech": "v.",
            "definition": "激活，启动",
            "english_definition": "to make operational",
            "difficulty": 3,
        },
        {
            "word": "active",
            "phonetic": "/ˈæktɪv/",
            "part_of_speech": "adj.",
            "definition": "活跃的，积极的",
            "english_definition": "engaging in action",
            "difficulty": 1,
        },
        {
            "word": "actively",
            "phonetic": "/ˈæktɪvli/",
            "part_of_speech": "adv.",
            "definition": "积极地，活跃地",
            "english_definition": "in an active manner",
            "difficulty": 2,
        },
        {
            "word": "activity",
            "phonetic": "/ækˈtɪvəti/",
            "part_of_speech": "n.",
            "definition": "活动，活跃",
            "english_definition": "a thing done",
            "difficulty": 1,
        },
        {
            "word": "actor",
            "phonetic": "/ˈæktər/",
            "part_of_speech": "n.",
            "definition": "演员",
            "english_definition": "a person who acts",
            "difficulty": 1,
        },
        {
            "word": "actress",
            "phonetic": "/ˈæktrəs/",
            "part_of_speech": "n.",
            "definition": "女演员",
            "english_definition": "a female actor",
            "difficulty": 1,
        },
        {
            "word": "actual",
            "phonetic": "/ˈæktʃuəl/",
            "part_of_speech": "adj.",
            "definition": "实际的，真实的",
            "english_definition": "existing in fact",
            "difficulty": 2,
        },
        {
            "word": "actually",
            "phonetic": "/ˈæktʃuəli/",
            "part_of_speech": "adv.",
            "definition": "实际上，事实上",
            "english_definition": "in fact",
            "difficulty": 1,
        },
        {
            "word": "acute",
            "phonetic": "/əˈkjuːt/",
            "part_of_speech": "adj.",
            "definition": "敏锐的，急性的",
            "english_definition": "sharp, intense",
            "difficulty": 3,
        },
        {
            "word": "adapt",
            "phonetic": "/əˈdæpt/",
            "part_of_speech": "v.",
            "definition": "适应，改编",
            "english_definition": "to adjust to new conditions",
            "difficulty": 2,
        },
        {
            "word": "adaptation",
            "phonetic": "/ˌædæpˈteɪʃn/",
            "part_of_speech": "n.",
            "definition": "适应，改编",
            "english_definition": "the process of adapting",
            "difficulty": 3,
        },
        {
            "word": "add",
            "phonetic": "/æd/",
            "part_of_speech": "v.",
            "definition": "添加，增加",
            "english_definition": "to join or combine",
            "difficulty": 1,
        },
        {
            "word": "addiction",
            "phonetic": "/əˈdɪkʃn/",
            "part_of_speech": "n.",
            "definition": "上瘾，沉溺",
            "english_definition": "being addicted",
            "difficulty": 3,
        },
        {
            "word": "additional",
            "phonetic": "/əˈdɪʃənl/",
            "part_of_speech": "adj.",
            "definition": "额外的，附加的",
            "english_definition": "added, extra",
            "difficulty": 2,
        },
        {
            "word": "additionally",
            "phonetic": "/əˈdɪʃənəli/",
            "part_of_speech": "adv.",
            "definition": "此外",
            "english_definition": "in addition",
            "difficulty": 2,
        },
        {
            "word": "address",
            "phonetic": "/əˈdres/",
            "part_of_speech": "n./v.",
            "definition": "地址，演讲；处理",
            "english_definition": "a place where someone lives",
            "difficulty": 1,
        },
        {
            "word": "adequate",
            "phonetic": "/ˈædɪkwət/",
            "part_of_speech": "adj.",
            "definition": "足够的，适当的",
            "english_definition": "satisfactory, acceptable",
            "difficulty": 2,
        },
        {
            "word": "adequately",
            "phonetic": "/ˈædɪkwətli/",
            "part_of_speech": "adv.",
            "definition": "充分地",
            "english_definition": "satisfactorily",
            "difficulty": 2,
        },
        {
            "word": "adjust",
            "phonetic": "/əˈdʒʌst/",
            "part_of_speech": "v.",
            "definition": "调整，适应",
            "english_definition": "to alter or move",
            "difficulty": 2,
        },
        {
            "word": "adjustment",
            "phonetic": "/əˈdʒʌstmənt/",
            "part_of_speech": "n.",
            "definition": "调整，调节",
            "english_definition": "a small change",
            "difficulty": 2,
        },
        {
            "word": "administer",
            "phonetic": "/ədˈmɪnɪstər/",
            "part_of_speech": "v.",
            "definition": "管理，执行",
            "english_definition": "to manage, to give out",
            "difficulty": 3,
        },
        {
            "word": "administration",
            "phonetic": "/ədˌmɪnɪˈstreɪʃn/",
            "part_of_speech": "n.",
            "definition": "管理，行政",
            "english_definition": "the management of affairs",
            "difficulty": 3,
        },
        {
            "word": "administrative",
            "phonetic": "/ədˈmɪnɪstreɪtɪv/",
            "part_of_speech": "adj.",
            "definition": "行政的，管理的",
            "english_definition": "relating to administration",
            "difficulty": 3,
        },
        {
            "word": "admire",
            "phonetic": "/ədˈmaɪər/",
            "part_of_speech": "v.",
            "definition": "钦佩，赞赏",
            "english_definition": "to regard with respect",
            "difficulty": 2,
        },
        {
            "word": "admission",
            "phonetic": "/ədˈmɪʃn/",
            "part_of_speech": "n.",
            "definition": "准许进入，承认",
            "english_definition": "the process of entering",
            "difficulty": 3,
        },
        {
            "word": "admit",
            "phonetic": "/ədˈmɪt/",
            "part_of_speech": "v.",
            "definition": "承认，准许",
            "english_definition": "to confess, to allow entry",
            "difficulty": 2,
        },
        {
            "word": "adopt",
            "phonetic": "/əˈdɒpt/",
            "part_of_speech": "v.",
            "definition": "采用，收养",
            "english_definition": "to take up, to take as one's own",
            "difficulty": 2,
        },
        {
            "word": "adoption",
            "phonetic": "/əˈdɒpʃn/",
            "part_of_speech": "n.",
            "definition": "采用，收养",
            "english_definition": "the act of adopting",
            "difficulty": 2,
        },
        {
            "word": "adult",
            "phonetic": "/ˈædʌlt/",
            "part_of_speech": "n./adj.",
            "definition": "成年人；成年的",
            "english_definition": "a fully grown person",
            "difficulty": 1,
        },
        {
            "word": "advance",
            "phonetic": "/ədˈvɑːns/",
            "part_of_speech": "v./n.",
            "definition": "前进，进步",
            "english_definition": "to move forward",
            "difficulty": 2,
        },
        {
            "word": "advanced",
            "phonetic": "/ədˈvɑːnst/",
            "part_of_speech": "adj.",
            "definition": "高级的，先进的",
            "english_definition": "far on in development",
            "difficulty": 2,
        },
        {
            "word": "advantage",
            "phonetic": "/ədˈvɑːntɪdʒ/",
            "part_of_speech": "n.",
            "definition": "优势，优点",
            "english_definition": "a beneficial feature",
            "difficulty": 2,
        },
        {
            "word": "adventure",
            "phonetic": "/ədˈventʃər/",
            "part_of_speech": "n.",
            "definition": "冒险，奇遇",
            "english_definition": "an unusual experience",
            "difficulty": 2,
        },
        {
            "word": "advertise",
            "phonetic": "/ˈædvətaɪz/",
            "part_of_speech": "v.",
            "definition": "做广告，宣传",
            "english_definition": "to promote",
            "difficulty": 2,
        },
        {
            "word": "advertisement",
            "phonetic": "/ədˈvɜːtɪsmənt/",
            "part_of_speech": "n.",
            "definition": "广告，宣传",
            "english_definition": "a notice or announcement",
            "difficulty": 2,
        },
        {
            "word": "advertising",
            "phonetic": "/ˈædvətaɪzɪŋ/",
            "part_of_speech": "n.",
            "definition": "广告业，广告",
            "english_definition": "the activity of advertising",
            "difficulty": 2,
        },
        {
            "word": "advice",
            "phonetic": "/ədˈvaɪs/",
            "part_of_speech": "n.",
            "definition": "建议，忠告",
            "english_definition": "guidance or recommendations",
            "difficulty": 1,
        },
        {
            "word": "advise",
            "phonetic": "/ədˈvaɪz/",
            "part_of_speech": "v.",
            "definition": "建议，劝告",
            "english_definition": "to offer suggestions",
            "difficulty": 2,
        },
        {
            "word": "advocate",
            "phonetic": "/ˈædvəkeɪt/",
            "part_of_speech": "v./n.",
            "definition": "提倡，拥护；倡导者",
            "english_definition": "to publicly support",
            "difficulty": 3,
        },
        {
            "word": "affair",
            "phonetic": "/əˈfeər/",
            "part_of_speech": "n.",
            "definition": "事务，事情",
            "english_definition": "an event or sequence",
            "difficulty": 2,
        },
        {
            "word": "affect",
            "phonetic": "/əˈfekt/",
            "part_of_speech": "v.",
            "definition": "影响，感动",
            "english_definition": "to make a difference to",
            "difficulty": 2,
        },
        {
            "word": "affection",
            "phonetic": "/əˈfekʃn/",
            "part_of_speech": "n.",
            "definition": "喜爱，感情",
            "english_definition": "a gentle feeling of fondness",
            "difficulty": 3,
        },
        {
            "word": "afford",
            "phonetic": "/əˈfɔːrd/",
            "part_of_speech": "v.",
            "definition": "负担得起，提供",
            "english_definition": "to have enough money",
            "difficulty": 2,
        },
        {
            "word": "afraid",
            "phonetic": "/əˈfreɪd/",
            "part_of_speech": "adj.",
            "definition": "害怕的，担心的",
            "english_definition": "feeling fear",
            "difficulty": 1,
        },
        {
            "word": "after",
            "phonetic": "/ˈɑːftər/",
            "part_of_speech": "prep./conj./adv.",
            "definition": "在...之后",
            "english_definition": "following in time",
            "difficulty": 1,
        },
        {
            "word": "afternoon",
            "phonetic": "/ˌɑːftərˈnuːn/",
            "part_of_speech": "n.",
            "definition": "下午",
            "english_definition": "the time from noon to evening",
            "difficulty": 1,
        },
        {
            "word": "afterward",
            "phonetic": "/ˈɑːftərwərd/",
            "part_of_speech": "adv.",
            "definition": "后来，以后",
            "english_definition": "at a later time",
            "difficulty": 2,
        },
        {
            "word": "again",
            "phonetic": "/əˈɡen/",
            "part_of_speech": "adv.",
            "definition": "再一次，又",
            "english_definition": "once more",
            "difficulty": 1,
        },
        {
            "word": "against",
            "phonetic": "/əˈɡenst/",
            "part_of_speech": "prep.",
            "definition": "反对，靠着",
            "english_definition": "in opposition to",
            "difficulty": 1,
        },
        {
            "word": "age",
            "phonetic": "/eɪdʒ/",
            "part_of_speech": "n./v.",
            "definition": "年龄，时代；变老",
            "english_definition": "the length of time alive",
            "difficulty": 1,
        },
        {
            "word": "aged",
            "phonetic": "/eɪdʒd/",
            "part_of_speech": "adj.",
            "definition": "年老的，...岁的",
            "english_definition": "old",
            "difficulty": 2,
        },
        {
            "word": "agency",
            "phonetic": "/ˈeɪdʒənsi/",
            "part_of_speech": "n.",
            "definition": "代理，中介",
            "english_definition": "a business or organization",
            "difficulty": 3,
        },
        {
            "word": "agenda",
            "phonetic": "/əˈdʒendə/",
            "part_of_speech": "n.",
            "definition": "议程，日程",
            "english_definition": "a list of items",
            "difficulty": 3,
        },
        {
            "word": "agent",
            "phonetic": "/ˈeɪdʒənt/",
            "part_of_speech": "n.",
            "definition": "代理人，特工",
            "english_definition": "a person who acts on behalf",
            "difficulty": 2,
        },
        {
            "word": "aggressive",
            "phonetic": "/əˈɡresɪv/",
            "part_of_speech": "adj.",
            "definition": "侵略的，有进取心的",
            "english_definition": "ready to attack",
            "difficulty": 3,
        },
        {
            "word": "ago",
            "phonetic": "/əˈɡoʊ/",
            "part_of_speech": "adv.",
            "definition": "以前",
            "english_definition": "before the present",
            "difficulty": 1,
        },
        {
            "word": "agree",
            "phonetic": "/əˈɡriː/",
            "part_of_speech": "v.",
            "definition": "同意，赞成",
            "english_definition": "to have the same opinion",
            "difficulty": 1,
        },
        {
            "word": "agreement",
            "phonetic": "/əˈɡriːmənt/",
            "part_of_speech": "n.",
            "definition": "协议，同意",
            "english_definition": "harmony or accordance",
            "difficulty": 2,
        },
    ]

    return words


def save_cet4_base():
    """保存CET-4基础词汇"""
    words = generate_cet4_words()

    # 保存到JSON文件
    output_dir = os.path.dirname(os.path.abspath(__file__))
    output_file = os.path.join(output_dir, "cet4_words_part1.json")

    with open(output_file, "w", encoding="utf-8") as f:
        json.dump(words, f, ensure_ascii=False, indent=2)

    print(f"已生成CET-4基础词汇: {len(words)} 个")
    print(f"保存位置: {output_file}")
    return words


if __name__ == "__main__":
    save_cet4_base()
    print("\n提示: 这是CET-4基础词汇A部分(100词)")
    print("完整版需要继续添加B-Z部分词汇")
